### ISSUE TITLE
Broken dependencies when using "max" resolution strategy

### ISSUE THREAD

**Issue by aggieben** [phnx47/Prometheus.Client.MetricServer#3]
I filed this issue in Paket first, but the more I look at this the more I think this is actually an issue with this package.  The dependency tree breaks when using a "max" resolution strategy (e.g., transitive dependencies are resolved using the highest compatible version number).  NuGet defaults to a "min" strategy, whereas Paket defaults to a "max" strategy, which might explain why this issue hasn't come up yet.

See here: https://github.com/fsprojects/Paket/issues/3015

I haven't yet been able to figure out where the breakage is really coming from yet, so any insight you might have into this could be helpful.

**Comment by malachib** [comment]
@aggieben If you look at https://github.com/phnx47/Prometheus.Client.MetricServer/commit/a3c73ed901885c6c3222b822589f74ea0974b652#diff-9856df1ba6c666269453df6fbac3a4a5 the near-last line `<PackageReference Include="Prometheus.Client" Version="[1.1.0,1.4.0)" />` there's an explicit "less than" rather than "less than or equal to" specification.  

When the author upgraded the client to 1.4.0 it went out of those bounds, thereby causing an issue if one uses client 1.4.0 in the same project.  I'm not 100% sure if this is the same issue you describe but it seems like it.  @phnx47 has merged in my pull request to address this but has yet to publish the update to nuget.org

**Comment by aggieben** [comment]
Nice catch @malachib, thanks for that.
